config/routes.rb
Rails.application.routes.draw do

  devise_for :clients

  authenticated :client do
    root 'home#index', as: :authenticated_client
  end

  # Home
  get 'home' => 'home#index', as: :home
  # About
  get 'about' => 'page#about', as: :about
  # login
  get 'login' => 'page#login', as: :login
  # signup
  get 'signup' => 'page#signup', as: :signup
  # user
  get 'user' => 'page#user', as: :user
  get 'user_edit_profile' => 'page#user_edit_profile', as: :user_edit_profile
  get 'user_edit_photo' => 'page#user_edit_photo', as: :user_edit_photo
  get 'user_edit_email' => 'page#user_edit_email', as: :user_edit_email
  get 'user_edit_password' => 'page#user_edit_password', as: :user_edit_password
  get 'user_edit_preference_email' => 'page#user_edit_preference_email', as: :user_edit_preference_email
  get 'user_address_list' => 'page#user_address_list', as: :user_address_list
  get 'user_add_address' => 'page#user_add_address', as: :user_add_address
  get 'user_historical_list' => 'page#user_historical_list', as: :user_historical_list
  get 'user_historical_view' => 'page#user_historical_view', as: :user_historical_view


  scope '/admin' do
    get 'addresses/get_client_addresses/:client_id' => 'addresses#get_client_addresses'
    get 'daily_menus/get_plates_from_date/:date/:request_id' => 'daily_menus#get_plates_from_date'

    resources :portal_banners
    resources :plate_ratings
    resources :chef_ratings
    resources :window_requests
    resources :request_statuses

    resources :requests do
      post :update_status
    end

    resources :chef_types
    resources :daily_menus
    resources :settings

    # resources :nutritional_tables
    resources :chefs do
      resources :addresses
    end

    resources :clients do
      resources :addresses
    end

    resources :addresses

    get 'chef_addresses/:chef_id' => 'addresses#index'

    resources :plates do
      post :nutritional_table
      post :activate
      post :deactivate
      post :daily_menu
    end

    resources :plate_badges
    resources :plate_accompaniments
    resources :plate_types
    resources :ingredients
    resources :badges
    resources :countries

    resources  :users_admin, :controller => 'users' do
      collection do
        patch 'update_password'
        patch 'update_all_passwords'
      end
    end

    devise_for :users

    resources :roles_permissions
    resources :permissions
    resources :roles
    resources :entities
    resources :modules_categories

    # You can have the root of your site routed with "root"
    root to: "dashboard#index"
  end
  #api
  namespace :api do
    namespace :v1 do
      post 'login' => 'sessions#login'
    end
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/plate.rb
class Plate < ActiveRecord::Base

	attr_accessor :quantity
	# belongs_to :chef
	belongs_to :plate_type
	belongs_to :chef
	belongs_to :nutritional_table
	has_and_belongs_to_many :plate_badges
	has_and_belongs_to_many  :ingredients, dependent: :restrict_with_error
	has_and_belongs_to_many  :plate_accompaniments
	
	has_many :request_plates, :inverse_of => :plate
	has_many :requests, :through => :request_plates

	validates :title, presence: true, uniqueness: true
	validates :plate_type_id, presence: true
	validates :description, presence: true, uniqueness: true
	validates :chef_id, presence: true
	validates :photo, presence: true
	has_attached_file :photo, styles: { medium: "300x300>", thumb: "64x64>" }
	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
	validates_attachment_size :photo, less_than: 2.megabytes

	accepts_nested_attributes_for :nutritional_table
	accepts_nested_attributes_for :ingredients
	accepts_nested_attributes_for :plate_badges
	accepts_nested_attributes_for :plate_accompaniments
	accepts_nested_attributes_for :requests
	accepts_nested_attributes_for :request_plates
end

app/models/plate_type.rb
class PlateType < ActiveRecord::Base
	has_many :plate, dependent: :restrict_with_error
	validates :name, presence: true, uniqueness: true
end

app/controllers/plates_controller.rb
class PlatesController < ApplicationController
  before_action :set_plate, only: [:show, :edit, :update, :destroy]

  # GET /plates
  # GET /plates.json
  def index
    @term = params[:term]
    @where = []    

    @where << "plates.title LIKE :term"    
    @where << "plates.description LIKE :term"    
    @where << "plates.price LIKE :term"    
    @where << "plates.available_quantity LIKE :term"    
    @where << "plate_types.name LIKE :term"    
    @where = @where.join(" OR ")

    @plates = Plate.joins(:plate_type).where(@where, term: "%#{params[:term]}%").paginate(:page => params[:page], :per_page => 10)
  end

  # GET /plates/1
  # GET /plates/1.json
  def show
  end

  # GET /plates/new
  def new
    @plate = Plate.new
    @types = PlateType.all
    @badges = PlateBadge.all
    @chefs = Chef.where('active = 1')
    @ingredients_list = Ingredient.all.map { |i| {text: i.name, value: i.id}}
    @plate_ingredients_list = @plate.ingredients.map { |i| {text: i.name, value: i.id} }
    @accompaniments_list = PlateAccompaniment.all.map { |p| {text: p.name, value: p.id}}
    @plate_accompaniments_list = @plate.plate_accompaniments.map { |p| {text: p.name, value: p.id} }
  end

  # GET /plates/1/edit
  def edit
    @types = PlateType.all
  end

  # POST /plates
  # POST /plates.json
  def create
    @plate = Plate.new(plate_params_with_ingredients_and_accompaniments)
    @plate.plate_badges.clear
    @types = PlateType.all
    @badges = PlateBadge.all
    @chefs = Chef.where('active = 1')

    respond_to do |format|
      if @plate.save
        format.html { redirect_to plates_url, :flash =>{:success => 'O prato foi criado com sucesso.' } }

        format.json { render :show, status: :created, location: @plate }
      else
        format.html { render :new }
        format.json { render json: @plate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plates/1
  # PATCH/PUT /plates/1.json
  def update
    @plate.plate_badges.clear
    respond_to do |format|
      if @plate.update(plate_params_with_ingredients_and_accompaniments)
        format.html { redirect_to plates_url, :flash =>{:success => 'O prato foi atualizado com sucesso.' } }
        format.json { render :show, status: :ok, location: @plate }
      else
        format.html { render :edit }
        format.json { render json: @plate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plates/1
  # DELETE /plates/1.json
  def destroy
    @plate.destroy
    respond_to do |format|
      format.html { redirect_to plates_url, :flash =>{:success => 'O prato foi removido com sucesso.' } }
      format.json { head :no_content }
    end
  end

  def activate
    @plate = Plate.find(params[:plate_id])
    @plate.active = 1
    @plate.save
    respond_to do |format|
      format.html { redirect_to :back, :flash =>{:success => 'O prato foi ativado com sucesso.' } }
      format.json { head :no_content }
    end
  end

  def deactivate
    @plate = Plate.find(params[:plate_id])
    @plate.active = 0
    @plate.save
    respond_to do |format|
      format.html { redirect_to :back, :flash =>{:success => 'O prato foi desativado com sucesso.' } }
      format.json { head :no_content }
    end
  end

  def daily_menu
    @plate = Plate.find(params[:plate_id])
    set_relations

    keys = ['sunday_available', 'monday_available', 'tuesday_available', 'wednesday_available', 
      'thursday_available', 'friday_available', 'saturday_available', ]
    keys.each { |k| params['plate'].has_key?(k) ? '' : params['plate'][k] = 0 }
    params['plate'].delete(['price_mask'])

    respond_to do |format|
      if @plate.update(plate_params)
        format.html { redirect_to :back, :flash =>{:success => 'O prato foi atualizado com sucesso.' } }
        format.json { render :show, status: :ok, location: @plate }
      else
        format.html { redirect_to :back, :flash =>{:alert => 'Erro ao salvar o Cardápio do Dia'} }
        format.json { render json: @plate.errors, status: :unprocessable_entity }
      end
    end
  end

  def nutritional_table
    @plate = Plate.find(params[:plate_id])
    respond_to do |format|
      if @plate.nutritional_table.nil?
        @nutritional_table = NutritionalTable.create(nutritional_table_params)
        @plate.nutritional_table = @nutritional_table
        @plate.save
        format.html { redirect_to :back, :flash =>{:success => 'A tabela nutricional foi atualizada com sucesso.' } }
        format.json { render :show, status: :ok, location: @plate }
      else
        @plate.nutritional_table.update(nutritional_table_params)
        format.html { redirect_to :back, :flash =>{:success => 'O tabela nutricional foi atualizada com sucesso.' } }
        format.json { render :show, status: :ok, location: @plate }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plate
      @plate = Plate.find(params[:id])
      set_relations
    end

    def set_relations
      @types = PlateType.all
      @badges = PlateBadge.all
      @chefs = Chef.where('active = 1')
      @ingredients_list = Ingredient.all.map { |i| {text: i.name, value: i.id}}
      @plate_ingredients_list = @plate.ingredients.map { |i| {text: i.name, value: i.id} }
      @accompaniments_list = PlateAccompaniment.all.map { |p| {text: p.name, value: p.id}}
      @plate_accompaniments_list = @plate.plate_accompaniments.map { |p| {text: p.name, value: p.id} }
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plate_params
      params.require(:plate).permit(:nutritional_table, :title, :description, :price, :available_quantity, :photo, :active, :chef_id, :plate_type_id, 
        :ingredients_id, :plate_accompaniment_id, :sunday_available, :monday_available, :tuesday_available, :wednesday_available,
        :thursday_available, :friday_available, :saturday_available, :plate_badge_ids => [], :ingredient_ids => [], :plate_accompaniment_ids => [],
        )
    end

    def nutritional_table_params
      params.require(:nutritional_table).permit(:energetic_value, :carbohydrate, :protein, :total_fat, :saturated_fat, :trans_fat, :dietary_fiber, :sodium, :iron)
    end

    def plate_params_with_ingredients_and_accompaniments
      ingredient_ids = plate_params['ingredient_ids'][0].split(',')
      plate_accompaniment_ids = plate_params['plate_accompaniment_ids'][0].split(',')
      params = plate_params
      params['ingredient_ids'] = ingredient_ids
      params['plate_accompaniment_ids'] = plate_accompaniment_ids
      return params
    end
end

app/helpers/plates_helper.rb
module PlatesHelper
	def get_plate_active_label plate
		(plate.active == 1) ? "Ativo" : "Inativo"
	end

	def get_formatted_energetic_value plate
		if plate.nutritional_table.nil?
			return '0'
		else
			return number_to_currency(plate.nutritional_table.energetic_value, unit: "", separator: ",", delimiter: ".")
		end
	end

	def get_energetic_value plate
		if plate.nutritional_table.nil?
			return '0'
		else
			return plate.nutritional_table.energetic_value.to_s
		end
	end

	def get_activate_or_deactivate_action_button plate
		if plate.active == 1 
          return link_to raw("<i class='fa fa-power-off'></i>"), '#deactivate_plate_'+plate.id.to_s, :class => 'btn btn-success tooltips', :'data-toggle' => 'modal', title: 'Desativar'  
        else 
          return link_to raw("<i class='fa fa-power-off'></i>"), '#activate_plate_'+plate.id.to_s, :class => 'btn btn-danger tooltips', :'data-toggle' => 'modal', title: 'Ativar'   
        end 
	end
end

app/views/plates/_activate_deactivate_plate_modal.html.erb
<% if plate.active == 1 %>
    <!-- MODAL DEACTIVATE -->
    <div class="modal fade modal-dialog-center in" id="deactivate_plate_<%= plate.id.to_s %>"
      tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">      
      <div class="modal-dialog ">
        <div class="modal-content-wrap">
          <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Desativar Prato</h4>
            </div>
            <div class="modal-body">
              <div class="text-center">
                Deseja Realmente Desativar o Prato?
              </div>
            </div>
            <div class="modal-footer">
              <div class="pull-left">
                <button data-dismiss="modal" class="btn btn-default" type="button">Fechar</button>
              </div>
              <%= link_to "Confirmar", plate_deactivate_path(plate), :method => :post, :class => 'btn btn-primary' %>
            </div>
          </div>
        </div>
      </div>
    </div>
<% else %>
  <!-- MODAL ACTIVATE -->
  <div class="modal fade modal-dialog-center in" id="activate_plate_<%= plate.id.to_s %>"
    tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">   
    <div class="modal-dialog ">
      <div class="modal-content-wrap">
        <div class="modal-content">
          <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
              <h4 class="modal-title">Ativar Prato</h4>
          </div>
          <div class="modal-body">
            <div class="text-center">
              Deseja Realmente Ativar o Prato?
            </div>
          </div>
          <div class="modal-footer">
            <div class="pull-left">
              <button data-dismiss="modal" class="btn btn-default" type="button">Fechar</button>
            </div>
            <%= link_to "Confirmar", plate_activate_path(plate), :method => :post, :class => 'btn btn-primary' %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/plates/_daily_menu_modal.html.erb
<!-- MODAL DAILY MENU -->
                  <div class="modal fade modal-dialog-center in" id="daily_menu_<%= plate.id.to_s %>"
                    tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
                    
                    <div class="modal-dialog ">
                      <div class="modal-content-wrap">
                        <div class="modal-content">
                          <div class="modal-header">
                              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                              <h4 class="modal-title">Adicionar ao Cardápio do Dia</h4>
                          </div>
                          <div class="modal-body">
                            <div class="panel-body">
                            <%= form_for plate, :url => plate_daily_menu_path(plate), :method => :post do |f| %>
                              <div class="form-group">
                                <%= f.label :price %><br>
                                <%= f.text_field 'price_mask', :value => number_to_currency(plate.price, unit: "R$", separator: ",", delimiter: "."), :class => 'form-control currency', :data => { 'prefix' => 'R$ ', 'thousands' => '.', 'decimal' => ',', 'group' => 'group_plate_' + plate.id.to_s} %>
                                <input type="hidden" id="plate[price]" name="plate[price]" value="<%= plate.price.to_s %>" data-group="group_plate_<%= plate.id %>" >
                              </div>

                              <div class="form-group">
                                <%= f.label :available_quantity %>
                                <%= number_field_tag 'plate[available_quantity]',  plate.available_quantity.to_s, class: 'form-control', min: 0 %>
                              </div>

                              <div class="form-group">
                                <%= check_box_tag "plate[sunday_available]", 1, plate.sunday_available == 1, {class: 'group_plate_' + plate.id.to_s} %>
                                <%= f.label :sunday_available %>
                              </div>
                              <div class="form-group">
                                <%= check_box_tag "plate[monday_available]", 1, plate.monday_available == 1, {class: 'group_plate_' + plate.id.to_s} %>
                                <%= f.label :monday_available %>
                              </div>
                              <div class="form-group">
                                <%= check_box_tag "plate[tuesday_available]", 1, plate.tuesday_available == 1, {class: 'group_plate_' + plate.id.to_s} %>
                                <%= f.label :tuesday_available %>
                              </div>
                              <div class="form-group">
                                <%= check_box_tag "plate[wednesday_available]", 1, plate.wednesday_available == 1, {class: 'group_plate_' + plate.id.to_s} %>
                                <%= f.label :wednesday_available %>
                              </div>
                              <div class="form-group">
                                <%= check_box_tag "plate[thursday_available]", 1, plate.thursday_available == 1, {class: 'group_plate_' + plate.id.to_s} %>
                                <%= f.label :thursday_available %>
                              </div>
                              <div class="form-group">
                                <%= check_box_tag "plate[friday_available]", 1, plate.friday_available == 1, {class: 'group_plate_' + plate.id.to_s} %>
                                <%= f.label :friday_available %>
                              </div>
                              <div class="form-group">
                                <%= check_box_tag "plate[saturday_available]", 1, plate.saturday_available == 1, {class: 'group_plate_' + plate.id.to_s} %>
                                <%= f.label :saturday_available %>
                              </div>
                              <div class="form-group">
                                <input type="checkbox" class="deselecting_all" name="group_plate_<%= plate.id.to_s %>">
                                <%= f.label "Desmarcar todos" %>
                              </div>
                            </div>
                          </div>
                          <div class="modal-footer">
                            <div class="pull-left">
                              <button data-dismiss="modal" class="btn btn-default" type="button">Fechar</button>
                            </div>
                            <div class="form-group">
                              <%= f.submit 'Salvar', :class => 'btn btn-primary' %>
                            </div>
                            <% end %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <!-- FIM MODAL DAILY MENU -->

app/views/plates/_form.html.erb
<div class="col-lg-12">
  <%= form_for @plate, html: { multipart: true } do |f| %>
      <%= link_to raw("<button type='button' class='btn btn-default'>Voltar</button>"), plates_path %>
  <div class="panel"></div>
  <section class="panel">
    <header class="panel-heading">
      Pratos
    </header>
    <% if @plate.errors.any? %>
      <div class="alert alert-danger">
        <% @plate.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </div>
    <% end %>
    <div class="panel-body">
                  <div class="form-group">
            <%= f.label 'Título*' %><br>
            <%= f.text_field :title, :class => 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label 'Descrição*' %><br>
            <%= f.text_area :description, :class => 'form-control summernote' %>
          </div>
         
          <div class="form-group">
            <%= f.label 'Foto*' %><br>
            <% if @plate.photo.exists? %>
              <%= image_tag @plate.photo.url(:thumb) %><br><br>
            <% end %>
            <%= f.file_field :photo, :class => 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label "Chef*" %><br>
            <%= f.select :chef_id, @chefs.collect {|type| [ type.name, type.id]}, {:prompt => 'Selecione o Chef'}, {:class => 'form-control'} %>
          </div>

          <div class="form-group">
            <%= f.label "Tipo*" %><br>
            <%= f.select :plate_type_id, @types.collect {|type| [ type.name, type.id]}, {:prompt => 'Selecione o Tipo'}, {:class => 'form-control'} %>
          </div>

          <div class="form-group">
            <%= f.label "Ingredientes" %><br>
            <%= f.text_field :ingredients, {class: '', "data-role": "ingredientsTags", value: '', name: 'plate[ingredient_ids][]'} %>
          </div>

          <div class="form-group">
            <%= f.label "Acompanhamentos" %><br>
            <%= f.text_field :plates_accompaniments, {class: '', "data-role": "accompanimentsTags", value: '', name: 'plate[plate_accompaniment_ids][]'} %>
          </div>

          <div class="form-group">
            <%= f.label "Badges" %><br>
              <div class="row">
                <% @badges.each do |badge| %>
                    <%= render '/plate_badges/plate_badges', b: badge, input: true  %>
                <% end %>
              </div>
          </div>
    </div>
  </section>
  <div class="form-group">
    <%= f.submit 'Salvar', :class => 'btn btn-primary' %>
  </div>
  <% end -%>
</div>
<link rel="stylesheet" href="//cdn.jsdelivr.net/bootstrap.tagsinput/0.4.2/bootstrap-tagsinput.css" />
<script type="text/javascript">
  window.addEventListener('load', function(){
    $('.summernote').each(function(){
      //$(this).summernote({height:300});
    });

    /* INGREDIENTES */
    var ingredientsList = <%= raw(@ingredients_list.to_json) %>;
    var plateIngredientsList = <%= raw(@plate_ingredients_list.to_json) %>;

    var tagsIngredients = $('[data-role="ingredientsTags"]');
    tagsIngredients.tagsinput({
      itemValue: 'value',
      itemText: 'text',
      allowDuplicates: false,
      onTagExists: function(item, $tag) {
        setTimeout(function(){
          tagsIngredients.tagsinput('input').val('');
        }, 50);
      },
      typeahead: {
        name: 'ingredients',
        displayKey: 'text',
        valueKey: 'value',
        source: ingredientsList
      }
    });

    //adiciona os já existentes
    plateIngredientsList.forEach( function(element, index) {
      tagsIngredients.tagsinput('add', {value: element.value, text: element.text});
    });

    //callback para limpar o txt após inserir um valor
    tagsIngredients.on('itemAdded', function(e) {
        console.log(tagsIngredients.tagsinput('input').val());
        setTimeout(function(){
          tagsIngredients.tagsinput('input').val('');
        }, 100);
    });

    /* ACOMPANHAMENTOS */
    var accompanimentList = <%= raw(@accompaniments_list.to_json) %>;
    var plateAccompanimentListList = <%= raw(@plate_accompaniments_list.to_json) %>;

    var tagsAccompaniments = $('[data-role="accompanimentsTags"]');
    tagsAccompaniments.tagsinput({
      itemValue: 'value',
      itemText: 'text',
      allowDuplicates: false,
      onTagExists: function(item, $tag) {
        setTimeout(function(){
          tagsAccompaniments.tagsinput('input').val('');
        }, 50);
      },
      typeahead: {
        name: 'accompaniments',
        displayKey: 'text',
        valueKey: 'value',
        source: accompanimentList
      }
    });

    //adiciona os já existentes
    plateAccompanimentListList.forEach( function(element, index) {
      tagsAccompaniments.tagsinput('add', {value: element.value, text: element.text});
    });

    //callback para limpar o txt após inserir um valor
    tagsAccompaniments.on('itemAdded', function(e) {
        console.log(tagsAccompaniments.tagsinput('input').val());
        setTimeout(function(){
          tagsAccompaniments.tagsinput('input').val('');
        }, 100);
    });

  });
</script>

app/views/plates/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= link_to raw("<button type='button' class='btn btn-primary'>Adicionar</button>"), new_plate_path %>
    <div class="panel"></div>
    <section class="panel">
      <header class="panel-heading">
          Pratos
          <% if @term %>
            <div class="pull-right">
              <%= link_to raw("<i class='fa fa-times'></i>"), plates_path, :class => 'btn btn-xs btn-shadow btn-danger tooltips', 'data-placement': 'top', title: 'Remover termo da pesquisa' %>
            </div>
          <% end %>
      </header>
      <div class="panel-body">
        <div class="pull-right">
          <%= form_tag(plates_path, method: 'GET') do -%>
              <input type="text" value="<%= @term %>" name="term" class="form-control search" placeholder="Digite o termo...">
          <% end %>
        </div>
        <section id="unseen">
          <table class="table table-bmoduleed table-striped table-condensed">
            <thead>
              <tr>
                  <th>Título</th>
                  <th>Descrição</th>
                  <th>Preço</th>
                  <th>Quantidade Disponível</th>
                  <th>Foto</th>
                  <th>Tipo de Prato</th>
                   <th colspan='3'>Ações</th>
              </tr>
            </thead>
            <tbody>
              <% @plates.each do |plate| %>
                <tr>
                                      <td><%= plate.title %></td>
                                      <td><%= sanitize plate.description %></td>
                                      <td><%= number_to_currency(plate.price, unit: "R$", separator: ",", delimiter: ".") %></td>
                                      <td><%= plate.available_quantity %></td>
                                      <td><%= image_tag(plate.photo.url(:thumb), size: "34x34") %></td>
                                      <td><%= plate.plate_type.name %></td>
                                    <td>
                    <!-- ATIVAR/DESATIVAR -->
                    <%= get_activate_or_deactivate_action_button plate %>
                    <!-- FIM ATIVAR/DESATIVAR -->
                    <%= link_to raw("<i class='fa fa-calendar'></i>"), '#daily_menu_'+plate.id.to_s, :class => 'btn btn-warning tooltips', :'data-toggle' => 'modal', title: 'Prato do dia' %>
                    <%= link_to raw("<i class='fa fa-list'></i>"), '#nutritional_table_'+plate.id.to_s, :class => 'btn btn-success tooltips', :'data-toggle' => 'modal', title: 'Tabela nutricional' %>
                    <%= link_to raw("<i class='fa fa-eye'></i>"), plate, :class => 'btn btn-primary tooltips', title: 'Visualizar' %>
                    <%= link_to raw("<i class='fa fa-pencil'></i>"), edit_plate_path(plate), :class => 'btn btn-info tooltips', title: 'Editar' %>
                    <%= link_to raw("<i class='fa fa-trash-o'></i>"), '#delete_plate_'+plate.id.to_s, :class => 'btn btn-danger tooltips', :'data-toggle' => 'modal',   title: 'Deletar'  %>
                  </td>
                </tr>
                <!-- MODAL DELETE -->
                <div class="modal fade modal-dialog-center in" id="delete_plate_<%= plate.id.to_s %>"
                  tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">                  
                  <div class="modal-dialog ">
                    <div class="modal-content-wrap">
                      <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h4 class="modal-title">Remover Prato</h4>
                        </div>
                        <div class="modal-body">
                          <div class="text-center">
                            Deseja Realmente Remover o Prato
                          </div>
                        </div>
                        <div class="modal-footer">
                          <div class="pull-left">
                            <button data-dismiss="modal" class="btn btn-default" type="button">Fechar</button>
                          </div>
                          <%= link_to raw("Confirmar"), plate, :class => 'btn btn-primary', :'data-method' => 'delete' %>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                  <%= render partial: 'activate_deactivate_plate_modal', locals: {plate: plate} %>
                  <%= render partial: 'daily_menu_modal', locals: {plate: plate} %>
                  <%= render partial: 'nutritional_table_modal', locals: {plate: plate} %>
              <% end -%>
            </tbody>
          </table>
          <div class="apple_pagination">
              <div class="page_info">
                  <%= page_entries_info @plates %>
              </div>
              <%= will_paginate @plates %>
          </div>
        </section>
      </div>
    </section>
  </div>
</div>

<script type="text/javascript">
  window.addEventListener('load', function(){

    $('.currency').maskMoney();

    $('.currency').keyup(function(e){
      var group = $(this).data('group');
      $('input[type="hidden"][data-group="' + group + '"]').val(($(this).maskMoney('unmasked')[0]));
      console.log($('input[type="hidden"][data-group="' + group + '"]').val());
    });

    $('.deselecting_all').on('change', function(){
      if (this.checked) {
        var group = $(this).attr('name');
        $('[class=' + group + ']').removeAttr('checked');
      }
    });

    $('.btn-clear').on('click', function(){
      var group = $(this).data('group');
      $('input.' + group + '[type=text]').val('');
      $('input[type="hidden"][data-group="' + group + '"]').val('');
    });
  });
</script>