config/routes.rb
Rails.application.routes.draw do

  devise_for :clients

  authenticated :client do
    root 'home#index', as: :authenticated_client
  end

  # Home
  get 'home' => 'home#index', as: :home
  # About
  get 'about' => 'page#about', as: :about
  # login
  get 'login' => 'page#login', as: :login
  # signup
  get 'signup' => 'page#signup', as: :signup
  # user
  get 'user' => 'page#user', as: :user
  get 'user_edit_profile' => 'page#user_edit_profile', as: :user_edit_profile
  get 'user_edit_photo' => 'page#user_edit_photo', as: :user_edit_photo
  get 'user_edit_email' => 'page#user_edit_email', as: :user_edit_email
  get 'user_edit_password' => 'page#user_edit_password', as: :user_edit_password
  get 'user_edit_preference_email' => 'page#user_edit_preference_email', as: :user_edit_preference_email
  get 'user_address_list' => 'page#user_address_list', as: :user_address_list
  get 'user_add_address' => 'page#user_add_address', as: :user_add_address
  get 'user_historical_list' => 'page#user_historical_list', as: :user_historical_list
  get 'user_historical_view' => 'page#user_historical_view', as: :user_historical_view


  scope '/admin' do
    get 'addresses/get_client_addresses/:client_id' => 'addresses#get_client_addresses'
    get 'daily_menus/get_plates_from_date/:date/:request_id' => 'daily_menus#get_plates_from_date'

    resources :portal_banners
    resources :plate_ratings
    resources :chef_ratings
    resources :window_requests
    resources :request_statuses

    resources :requests do
      post :update_status
    end

    resources :chef_types
    resources :daily_menus
    resources :settings

    # resources :nutritional_tables
    resources :chefs do
      resources :addresses
    end

    resources :clients do
      resources :addresses
    end

    resources :addresses

    get 'chef_addresses/:chef_id' => 'addresses#index'

    resources :plates do
      post :nutritional_table
      post :activate
      post :deactivate
      post :daily_menu
    end

    resources :plate_badges
    resources :plate_accompaniments
    resources :plate_types
    resources :ingredients
    resources :badges
    resources :countries

    resources  :users_admin, :controller => 'users' do
      collection do
        patch 'update_password'
        patch 'update_all_passwords'
      end
    end

    devise_for :users

    resources :roles_permissions
    resources :permissions
    resources :roles
    resources :entities
    resources :modules_categories

    # You can have the root of your site routed with "root"
    root to: "dashboard#index"
  end
  #api
  namespace :api do
    namespace :v1 do
      post 'login' => 'sessions#login'
    end
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/plate_accompaniment.rb
class PlateAccompaniment < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true

	has_and_belongs_to_many :plates
	before_destroy :has_plates?

	def has_plates?
		if self.plates.any? 
			errors.add(:base, I18n.t('errors.messages.restrict_dependent_destroy.one'))
			return false
		end
	end
end

app/controllers/plate_accompaniments_controller.rb
class PlateAccompanimentsController < ApplicationController
  before_action :set_plate_accompaniment, only: [:show, :edit, :update, :destroy]

  # GET /plate_accompaniments
  # GET /plate_accompaniments.json
  def index
    @term = params[:term]
    @where = []    

    @where << "plate_accompaniments.name LIKE :term"    
    @where = @where.join(" OR ")

    @plate_accompaniments = PlateAccompaniment.where(@where, term: "%#{params[:term]}%").paginate(:page => params[:page], :per_page => 10)
  end

  # GET /plate_accompaniments/1
  # GET /plate_accompaniments/1.json
  def show
  end

  # GET /plate_accompaniments/new
  def new
    @plate_accompaniment = PlateAccompaniment.new
  end

  # GET /plate_accompaniments/1/edit
  def edit
  end

  # POST /plate_accompaniments
  # POST /plate_accompaniments.json
  def create
    @plate_accompaniment = PlateAccompaniment.new(plate_accompaniment_params)

    respond_to do |format|
      if @plate_accompaniment.save
        format.html { redirect_to plate_accompaniments_url, :flash =>{:success => 'O acompanhamento de prato foi criado com sucesso.' } }

        format.json { render :show, status: :created, location: @plate_accompaniment }
      else
        format.html { render :new }
        format.json { render json: @plate_accompaniment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plate_accompaniments/1
  # PATCH/PUT /plate_accompaniments/1.json
  def update
    respond_to do |format|
      if @plate_accompaniment.update(plate_accompaniment_params)
        format.html { redirect_to plate_accompaniments_url, :flash =>{:success => 'O acompanhamento de prato foi atualizado com sucesso.' } }
        format.json { render :show, status: :ok, location: @plate_accompaniment }
      else
        format.html { render :edit }
        format.json { render json: @plate_accompaniment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plate_accompaniments/1
  # DELETE /plate_accompaniments/1.json
  def destroy
    @plate_accompaniment.destroy
    respond_to do |format|
      if not @plate_accompaniment.errors.any?
        format.html { redirect_to plate_accompaniments_url, :flash =>{:success => 'O acompanhamento de prato foi removido com sucesso.' } }
        format.json { head :no_content }
      else
        format.html { redirect_to plate_accompaniments_url, alert: @plate_accompaniment.errors.full_messages.join('<br>') }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plate_accompaniment
      @plate_accompaniment = PlateAccompaniment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plate_accompaniment_params
      params.require(:plate_accompaniment).permit(:name)
    end
end

app/helpers/plate_accompaniments_helper.rb
module PlateAccompanimentsHelper
end

app/views/plate_accompaniments/_form.html.erb
<div class="col-lg-12">
  <%= form_for(@plate_accompaniment) do |f| %>
  <%= link_to raw("<button type='button' class='btn btn-default'>Voltar</button>"), plate_accompaniments_path %>
  <div class="panel"></div>
  <section class="panel">
  <header class="panel-heading">
    Acompanhamento
  </header>
    <% if @plate_accompaniment.errors.any? %>
      <div class="alert alert-danger">
        <% @plate_accompaniment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </div>
    <% end %>
    <div class="panel-body">
                  <div class="form-group">
            <%= f.label "Nome*" %><br>
            <%= f.text_field :name, :class => 'form-control' %>
          </div>
    </div>
  </section>
    <div class="form-group">
      <%= f.submit 'Salvar', :class => 'btn btn-primary' %>
    </div>
    <% end -%>
</div>

app/views/plate_accompaniments/index.html.erb
<%= render file: 'dashboard/dashboard' %>
<div class="row">
  <div class="col-lg-12">
    <%= link_to raw("<button type='button' class='btn btn-primary'>Adicionar</button>"), new_plate_accompaniment_path %>
    <div class="panel"></div>
    <section class="panel">
      <header class="panel-heading">
          Acompanhamentos
          <% if @term %>
            <div class="pull-right">
              <%= link_to raw("<i class='fa fa-times'></i>"), plate_accompaniments_path, :class => 'btn btn-xs btn-shadow btn-danger tooltips', 'data-placement': 'top', title: 'Remover termo da pesquisa' %>
            </div>
          <% end %>
      </header>
      <div class="panel-body">
        <div class="pull-right">
            <%= form_tag(plate_accompaniments_path, method: 'GET') do -%>
              <input type="text" value="<%= @term %>" name="term" class="form-control search" placeholder="Digite o termo...">
            <% end %>
        </div>
        <section id="unseen">
          <table class="table table-bmoduleed table-striped table-condensed">
            <thead>
              <tr>
                                  <th>Nome</th>
                                <th colspan='3'>Ações</th>
              </tr>
            </thead>
            <tbody>
              <% @plate_accompaniments.each do |plate_accompaniment| %>
                <tr>
                                      <td><%= plate_accompaniment.name %></td>
                                    <td>
                    <%= link_to raw("<i class='fa fa-eye'></i>"), plate_accompaniment, :class => 'btn btn-primary tooltips', 'data-placement': 'top', title: 'Visualizar' %>
                    <%= link_to raw("<i class='fa fa-pencil'></i>"), edit_plate_accompaniment_path(plate_accompaniment), :class => 'btn btn-info tooltips', 'data-placement': 'top', title: 'Editar' %>
                    <%= link_to raw("<i class='fa fa-trash-o'></i>"), '#delete_plate_accompaniment_'+plate_accompaniment.id.to_s, :class => 'btn btn-danger tooltips', :'data-toggle' => 'modal', 'data-placement': 'top', title: 'Deletar'  %>
                  </td>
                </tr>
                <div class="modal fade modal-dialog-center in" id="delete_plate_accompaniment_<%= plate_accompaniment.id.to_s %>"
                  tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
                <div class="modal-dialog ">
                  <div class="modal-content-wrap">
                    <div class="modal-content">
                      <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                          <h4 class="modal-title">Remover Acompanhamento</h4>
                      </div>
                      <div class="modal-body">
                        <div class="text-center">
                          Deseja Realmente Remover o Acompanhamento
                        </div>
                      </div>
                      <div class="modal-footer">
                        <div class="pull-left">
                          <button data-dismiss="modal" class="btn btn-default" type="button">Fechar</button>
                        </div>
                        <%= link_to raw("Confirmar"), plate_accompaniment, :class => 'btn btn-primary', :'data-method' => 'delete' %>
                      </div>
                    </div>
                  </div>
                </div>
              <% end -%>
            </tbody>
          </table>
          <div class="apple_pagination">
              <div class="page_info">
                  <%= page_entries_info @plate_accompaniments %>
              </div>
              <%= will_paginate @plate_accompaniments %>
          </div>
        </section>
      </div>
    </section>
  </div>
</div>

app/views/plate_accompaniments/show.html.erb
<div class="col-lg-12">
  <%= link_to raw("<button type='button' class='btn btn-default'>Voltar</button>"), plate_accompaniments_path %>
  <div class="panel"></div>
	<section class="panel">
    <div class="panel-heading">
        <div class="panel-title">Detalhes</div>
    </div>
    <div class="panel-body form-horizontal">
    		      <div class="form-group">
          <label for="number" class="control-label col-lg-3">Nome</label>
          <div class="col-lg-9">
            <label for="number" class="form-control-static"><%= @plate_accompaniment.name %></label>
          </div>
	      </div>
	        </div>
  </section>
</div>