config/routes.rb
Rails.application.routes.draw do

  devise_for :clients

  authenticated :client do
    root 'home#index', as: :authenticated_client
  end

  # Home
  get 'home' => 'home#index', as: :home
  # About
  get 'about' => 'page#about', as: :about
  # login
  get 'login' => 'page#login', as: :login
  # signup
  get 'signup' => 'page#signup', as: :signup
  # user
  get 'user' => 'page#user', as: :user
  get 'user_edit_profile' => 'page#user_edit_profile', as: :user_edit_profile
  get 'user_edit_photo' => 'page#user_edit_photo', as: :user_edit_photo
  get 'user_edit_email' => 'page#user_edit_email', as: :user_edit_email
  get 'user_edit_password' => 'page#user_edit_password', as: :user_edit_password
  get 'user_edit_preference_email' => 'page#user_edit_preference_email', as: :user_edit_preference_email
  get 'user_address_list' => 'page#user_address_list', as: :user_address_list
  get 'user_add_address' => 'page#user_add_address', as: :user_add_address
  get 'user_historical_list' => 'page#user_historical_list', as: :user_historical_list
  get 'user_historical_view' => 'page#user_historical_view', as: :user_historical_view


  scope '/admin' do
    get 'addresses/get_client_addresses/:client_id' => 'addresses#get_client_addresses'
    get 'daily_menus/get_plates_from_date/:date/:request_id' => 'daily_menus#get_plates_from_date'

    resources :portal_banners
    resources :plate_ratings
    resources :chef_ratings
    resources :window_requests
    resources :request_statuses

    resources :requests do
      post :update_status
    end

    resources :chef_types
    resources :daily_menus
    resources :settings

    # resources :nutritional_tables
    resources :chefs do
      resources :addresses
    end

    resources :clients do
      resources :addresses
    end

    resources :addresses

    get 'chef_addresses/:chef_id' => 'addresses#index'

    resources :plates do
      post :nutritional_table
      post :activate
      post :deactivate
      post :daily_menu
    end

    resources :plate_badges
    resources :plate_accompaniments
    resources :plate_types
    resources :ingredients
    resources :badges
    resources :countries

    resources  :users_admin, :controller => 'users' do
      collection do
        patch 'update_password'
        patch 'update_all_passwords'
      end
    end

    devise_for :users

    resources :roles_permissions
    resources :permissions
    resources :roles
    resources :entities
    resources :modules_categories

    # You can have the root of your site routed with "root"
    root to: "dashboard#index"
  end
  #api
  namespace :api do
    namespace :v1 do
      post 'login' => 'sessions#login'
    end
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/chef_rating.rb
class ChefRating < ActiveRecord::Base
  belongs_to :client
  belongs_to :chef

  validates :client_id, :chef_id, :score, :presence => true

  validate :client_already_rated_the_chef?

  def client_already_rated_the_chef?
  	errors.add('Cliente', 'Você já deu uma nota para este Chef') unless ChefRating::where('client_id = ? AND chef_id = ?', self.client_id, self.chef_id).first.nil?
  end
end

app/controllers/chef_ratings_controller.rb
class ChefRatingsController < ApplicationController
  before_action :set_chef_rating, only: [:show, :edit, :update, :destroy]

  # GET /chef_ratings
  def index    
    @term = params[:term]
    @where = []
    
    @where << "chef_ratings" + '.' + "client_id" + ' LIKE :term' 
    
    @where << "chefs" + '.' + "name" + ' LIKE :term' 
    
    @where << "chef_ratings" + '.' + "score" + ' LIKE :term' 
    
    @where = @where.join(" OR ")
    
    if params[:term].present?
      @chef_ratings = ChefRating.where(@where, term: "%#{params[:term]}%").paginate(:page => params[:page], :per_page => 10)
    else
      @chef_ratings = ChefRating.paginate(:page => params[:page], :per_page => 10)
    end
  
  end

  # GET /chef_ratings/1
  def show
  end

  # GET /chef_ratings/new
  def new
    @chef_rating = ChefRating.new
    @chefs = Chef.all
    @clients = Client.all
  end

  # GET /chef_ratings/1/edit
  def edit
  end

  # POST /chef_ratings
  def create
    @chef_rating = ChefRating.new(chef_rating_params)
    @chefs = Chef.all
    @clients = Client.all

    if @chef_rating.save
      redirect_to chef_ratings_path, :flash =>{:success => 'Rating de Chef foi criado com sucesso.' }
    else
      render :new
    end
  end

  # PATCH/PUT /chef_ratings/1
  def update
    if @chef_rating.update(chef_rating_params)
      redirect_to chef_ratings_path, :flash =>{:success => 'Rating de Chef foi atualizado com sucesso.' }
    else
      render :edit
    end
  end

  # DELETE /chef_ratings/1
  def destroy
    @chef_rating.destroy
    redirect_to chef_ratings_path, :flash =>{:success => 'Rating de Chef foi removido com sucesso.' }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chef_rating
      @chef_rating = ChefRating.find(params[:id])
      @chefs = Chef.all
      @clients = Client.all
    end

    # Only allow a trusted parameter "white list" through.
    def chef_rating_params
      params.require(:chef_rating).permit(:client_id, :chef_id, :score)
    end
end

app/helpers/chef_ratings_helper.rb
module ChefRatingsHelper
end

app/views/chef_ratings/_form.html.erb
<div class="col-lg-12">
  <%= form_for(@chef_rating) do |f| %>  
  <%= link_to raw("<button type='button' class='btn btn-default'>Voltar</button>"), chef_ratings_path %>
  <div class="panel"></div>
  <section class="panel">
    <header class="panel-heading">
       Rating de Chef
    </header>
    <% if @chef_rating.errors.any? %>
      <div class="alert alert-danger">
        <% @chef_rating.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </div>
    <% end %>
    <div class="panel-body">
                  <div class="form-group">
            <%= f.label 'Cliente*' %><br>
            <%= f.select :client_id, @clients.collect {|client| [ client.name, client.id]}, {:prompt => 'Selecione o Cliente'}, {:class => 'form-control'} %>
          </div>
                  <div class="form-group">
            <%= f.label 'Chef*' %><br>
            <%= f.select :chef_id, @chefs.collect {|type| [ type.name, type.id]}, {:prompt => 'Selecione o Chef'}, {:class => 'form-control'} %>
          </div>
                  <div class="form-group">
            <%= f.label 'Score*' %><br>
            <%= f.number_field :score, :class => 'form-control' %>
          </div>
            </div>
  </section>
  <div class="form-group">
      <%= f.submit 'Salvar', :class => 'btn btn-primary' %>
  </div>
  <% end -%>
</div>

app/views/chef_ratings/edit.html.erb
<%= render 'form' %>

app/views/chef_ratings/index.html.erb
<div class="row">
  <div class="col-lg-12">    
    <%= link_to raw("<button type='button' class='btn btn-primary'>Adicionar Rating de Chef</button>"), new_chef_rating_path %>
    <div class="panel"></div>
    <section class="panel">
      <header class="panel-heading">
          Rating de Chefs
          <% if @term %>
            <div class="pull-right">
              <%= link_to raw("<i class='fa fa-times'></i>"), chef_ratings_path, :class => 'btn btn-xs btn-shadow btn-danger tooltips', 'data-toggle': 'tooltip', 'data-placement': 'top', title: 'Remover termo da pesquisa' %>
            </div>
          <% end %>
      </header>
      <div class="panel-body">
        <div class="pull-right">
            <%= form_tag(chef_ratings_path, method: 'GET') do -%>
                <input type="text" value=""name="term" class="form-control search" placeholder="Digite o termo...">
            <% end %>
        </div>
        <section id="unseen">
          <table class="table table-bmoduleed table-striped table-condensed">
            <thead>
              <tr>
                                  <th>Cliente</th>
                                  <th>Chef</th>
                                  <th>Score</th>
                                <th colspan='3'>Ações</th>
              </tr>
            </thead>
            <tbody>
              <% @chef_ratings.each do |chef_rating| %>
                <tr>
                                      <td><%= chef_rating.client.name %></td>
                                      <td><%= chef_rating.chef.name %></td>
                                      <td><%= chef_rating.score %></td>
                                    <td>
                    <%= link_to raw("<i class='fa fa-eye'></i>"), chef_rating, :class => 'btn btn-primary tooltips', 'data-placement': 'top', title: 'Visualizar' %>
                    <%= link_to raw("<i class='fa fa-pencil'></i>"), edit_chef_rating_path(chef_rating), :class => 'btn btn-info tooltips', 'data-placement': 'top', title: 'Editar' %>
                    <%= link_to raw("<i class='fa fa-trash-o '></i>"), '#delete_chef_rating_'+chef_rating.id.to_s, :class => 'btn btn-danger tooltips', 'data-placement': 'top', title: 'Deletar', :'data-toggle' => 'modal'  %>
                  </td>
                </tr>
                <div class="modal fade modal-dialog-center in" id="delete_chef_rating_<%= chef_rating.id.to_s %>"
                  tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
                <div class="modal-dialog ">
                  <div class="modal-content-wrap">
                    <div class="modal-content">
                      <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                          <h4 class="modal-title">Remover Rating de Chef</h4>
                      </div>
                      <div class="modal-body">
                        <div class="text-center">
                          Deseja Realmente Remover o Rating de Chef
                        </div>
                      </div>
                      <div class="modal-footer">
                        <div class="pull-left">
                          <button data-dismiss="modal" class="btn btn-default" type="button">Fechar</button>
                        </div>
                        <%= link_to raw("Confirmar"), chef_rating, :class => 'btn btn-primary', :'data-method' => 'delete' %>
                      </div>
                    </div>
                  </div>
                </div>
                </div>
              <% end -%>
            </tbody>
          </table>
          <div class="apple_pagination">
              <div class="page_info">
                  <%= page_entries_info @chef_ratings %>
              </div>
              <%= will_paginate @chef_ratings %>
          </div>
        </section>
      </div>
    </section>
  </div>
</div>

app/views/chef_ratings/new.html.erb
<%= render 'form' %>

app/views/chef_ratings/show.html.erb
<div class="col-lg-12">  
  <%= link_to raw("<button type='button' class='btn btn-default'>Voltar</button>"), chef_ratings_path %>
  <div class="panel"></div>
	<section class="panel">
    <div class="panel-heading">
        <div class="panel-title">Detalhes</div>
    </div>
    <div class="panel-body form-horizontal">
    		      <div class="form-group">
          <label for="number" class="control-label col-lg-3">Cliente</label>
          <div class="col-lg-9">
            <label for="number" class="form-control-static"><%= @chef_rating.client.name %></label>
          </div>
	      </div>
	    	      <div class="form-group">
          <label for="number" class="control-label col-lg-3">Chef</label>
          <div class="col-lg-9">
            <label for="number" class="form-control-static"><%= @chef_rating.chef.name %></label>
          </div>
	      </div>
	    	      <div class="form-group">
          <label for="number" class="control-label col-lg-3">Score</label>
          <div class="col-lg-9">
            <label for="number" class="form-control-static"><%= @chef_rating.score %></label>
          </div>
	      </div>
	        </div>
  </section>
</div>