config/routes.rb
Rails.application.routes.draw do

  devise_for :clients

  authenticated :client do
    root 'home#index', as: :authenticated_client
  end

  # Home
  get 'home' => 'home#index', as: :home
  # About
  get 'about' => 'page#about', as: :about
  # login
  get 'login' => 'page#login', as: :login
  # signup
  get 'signup' => 'page#signup', as: :signup
  # user
  get 'user' => 'page#user', as: :user
  get 'user_edit_profile' => 'page#user_edit_profile', as: :user_edit_profile
  get 'user_edit_photo' => 'page#user_edit_photo', as: :user_edit_photo
  get 'user_edit_email' => 'page#user_edit_email', as: :user_edit_email
  get 'user_edit_password' => 'page#user_edit_password', as: :user_edit_password
  get 'user_edit_preference_email' => 'page#user_edit_preference_email', as: :user_edit_preference_email
  get 'user_address_list' => 'page#user_address_list', as: :user_address_list
  get 'user_add_address' => 'page#user_add_address', as: :user_add_address
  get 'user_historical_list' => 'page#user_historical_list', as: :user_historical_list
  get 'user_historical_view' => 'page#user_historical_view', as: :user_historical_view


  scope '/admin' do
    get 'addresses/get_client_addresses/:client_id' => 'addresses#get_client_addresses'
    get 'daily_menus/get_plates_from_date/:date/:request_id' => 'daily_menus#get_plates_from_date'

    resources :portal_banners
    resources :plate_ratings
    resources :chef_ratings
    resources :window_requests
    resources :request_statuses

    resources :requests do
      post :update_status
    end

    resources :chef_types
    resources :daily_menus
    resources :settings

    # resources :nutritional_tables
    resources :chefs do
      resources :addresses
    end

    resources :clients do
      resources :addresses
    end

    resources :addresses

    get 'chef_addresses/:chef_id' => 'addresses#index'

    resources :plates do
      post :nutritional_table
      post :activate
      post :deactivate
      post :daily_menu
    end

    resources :plate_badges
    resources :plate_accompaniments
    resources :plate_types
    resources :ingredients
    resources :badges
    resources :countries

    resources  :users_admin, :controller => 'users' do
      collection do
        patch 'update_password'
        patch 'update_all_passwords'
      end
    end

    devise_for :users

    resources :roles_permissions
    resources :permissions
    resources :roles
    resources :entities
    resources :modules_categories

    # You can have the root of your site routed with "root"
    root to: "dashboard#index"
  end
  #api
  namespace :api do
    namespace :v1 do
      post 'login' => 'sessions#login'
    end
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/badge.rb
class Badge < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true
	validates :description, presence: true, uniqueness: true
	validates :image, presence: true
	has_attached_file :image, styles: { medium: "300x300>", thumb: "64x64>" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	validates_attachment_size :image, less_than: 2.megabytes
	has_and_belongs_to_many :chefs, dependent: :restrict_with_error
end

app/models/chef.rb
class Chef < ActiveRecord::Base
  has_many :plates, dependent: :restrict_with_error
  belongs_to :country
  belongs_to :chef_type
  has_many :addresses
  has_and_belongs_to_many :badges

  validates :chef_type_id, presence: true
  validates :name, presence: true
  validates :cpf, presence: true, uniqueness: true
  validates :rg, presence: true, uniqueness: true
  validates :born_date, presence: true
  validates :country_id, presence: true
  validates :email, presence: true, uniqueness: true
  validates :specialty, presence: true
  validates :naturalness, presence: true
  validates :academic_education, presence: true
  validates :university, presence: true
  validates :photo, presence: true 

  has_attached_file :photo, styles: { medium: "300x300>", thumb: "64x64>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
  validates_with AttachmentSizeValidator, attributes: :photo, less_than: 2.megabytes

  def active?
    return 'Sim' if self.active
    'Não'
  end
  
  def age
    dob = self.born_date
    today = Date.today
    d = Date.new(today.year, dob.month, dob.day)
    age = d.year - dob.year - (d > today ? 1 : 0)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :set_badge, only: [:show, :edit, :update, :destroy]

  # GET /badges
  # GET /badges.json
  def index
    @term = params[:term]
    @where = []    
    @where << "badges.name LIKE :term"
    @where = @where.join(" OR ")
    @badges = Badge.where(@where, term: "%#{params[:term]}%").paginate(:page => params[:page], :per_page => 10)
  end

  # GET /badges/1
  # GET /badges/1.json
  def show
  end

  # GET /badges/new
  def new
    @badge = Badge.new
  end

  # GET /badges/1/edit
  def edit
  end

  # POST /badges
  # POST /badges.json
  def create
    @badge = Badge.new(badge_params)

    respond_to do |format|
      if @badge.save
        format.html { redirect_to badges_url, :flash => {:success => 'O badge foi criado com sucesso.' } }
        format.json { render :show, status: :created, location: @badge }
      else
        format.html { render :new }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /badges/1
  # PATCH/PUT /badges/1.json
  def update
    respond_to do |format|
      if @badge.update(badge_params)
        format.html { redirect_to badges_url, :flash => {:success => 'O badge foi atualizado com sucesso.' } }
        format.json { render :show, status: :ok, location: @badge }
      else
        format.html { render :edit }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /badges/1
  # DELETE /badges/1.json
  def destroy
    @badge.image = nil
    @badge.destroy
    respond_to do |format|
      format.html { redirect_to badges_url, :flash =>{:success => 'O Badge foi removido com sucesso.' } } 
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_badge
      @badge = Badge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def badge_params
      params.require(:badge).permit(:name, :description, :image)
    end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/badges/_badges.html.erb
<% unless b.nil? %>
    <div class="col-xs-6 col-md-2">
      <div href="#" class="thumbnail tooltips" data-placement='top' title="<%= b.name + ' - ' +b.description %>">
        <%= image_tag b.image.url(:thumb) %>
        <% if defined? input %>
        	<p class="text-center">     	        		
                <%= check_box_tag "chef[badge_ids][]", b.id, @chef.badges.include?(b), {class: ''} %>
        	</p>
        <% end %>       
      </div>
    </div>     
<% end %>

app/views/badges/_form.html.erb
<div class="col-lg-12">
  <%= form_for @badge, html: {multipart: true} do |f| %>
    <%= link_to raw("<button type='button' class='btn btn-default'>Voltar</button>"), badges_path %>
  <div class="panel"></div>
  <section class="panel">
    <header class="panel-heading">
          Chefs - Bagdes
    </header>
    <% if @badge.errors.any? %>
      <div class="alert alert-danger">
        <% @badge.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </div>
    <% end %>
    <div class="panel-body">
          <div class="form-group">
            <%= f.label "Nome*" %><br>
            <%= f.text_field :name, :class => 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label "Descrição*" %><br>
            <%= f.text_area :description, :class => 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label "Imagem*" %><br>
            <% if @badge.image.exists? %>
              <%= image_tag @badge.image.url(:thumb) %><br><br>
            <% end %>
            <%= f.file_field :image %>
          </div>
    </div>
  </section>
<div class="form-group">
  <%= f.submit 'Salvar', :class => 'btn btn-primary' %>
</div>
<% end -%>
</div>

app/views/badges/index.html.erb
<% if notice %>
  <div class="alert alert-block alert-success fade in">
      <%= notice %>
  </div>
<% end %>
<div class="row">
  <div class="col-lg-12">
    <%= link_to raw("<button type='button' class='btn btn-primary'>Adicionar</button>"), new_badge_path %>
    <div class="panel"></div>
    <section class="panel">
      <header class="panel-heading">
          Badges
          <% if @term %>
            <div class="pull-right">
              <%= link_to raw("<i class='fa fa-times'></i>"), badges_path, :class => 'btn btn-xs btn-shadow btn-danger tooltips', 'data-placement': 'top', title: 'Remover termo da pesquisa' %>
            </div>
          <% end %>
      </header>
      <div class="panel-body">
        <div class="pull-right">
            <%= form_tag(badges_path, method: 'GET') do -%>
                <input type="text" value="<%= @term %>" name="term" class="form-control search" placeholder="Digite o termo...">
            <% end %>
        </div>
        <section id="unseen">
          <table class="table table-bmoduleed table-striped table-condensed">
            <thead>
              <tr>
                                  <th>Nome</th>
                                  <th>Descrição</th>
                                  <th>Imagem</th>
                                <th colspan='3'>Ações</th>
              </tr>
            </thead>
            <tbody>
              <% @badges.each do |badge| %>
                <tr>
                                      <td><%= badge.name %></td>
                                      <td><%= badge.description %></td>
                                      <td><%= image_tag(badge.image.url(:thumb), size: "34x34") %></td>
                                    <td>
                    <%= link_to raw("<i class='fa fa-eye'></i>"), badge, :class => 'btn btn-primary tooltips', 'data-placement': 'top', title: 'Visualizar' %>
                    <%= link_to raw("<i class='fa fa-pencil'></i>"), edit_badge_path(badge), :class => 'btn btn-info tooltips', 'data-placement': 'top', title: 'Editar' %>
                    <%= link_to raw("<i class='fa fa-trash-o'></i>"), '#delete_badge_'+badge.id.to_s, :class => 'btn btn-danger tooltips', :'data-toggle' => 'modal', 'data-placement': 'top', title: 'Deletar'  %>
                  </td>
                </tr>
                <div class="modal fade modal-dialog-center in" id="delete_badge_<%= badge.id.to_s %>"
                  tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
                <div class="modal-dialog ">
                  <div class="modal-content-wrap">
                    <div class="modal-content">
                      <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                          <h4 class="modal-title">Remover Badge</h4>
                      </div>
                      <div class="modal-body">
                        <div class="text-center">
                          Deseja Realmente Remover o Badge
                        </div>
                      </div>
                      <div class="modal-footer">
                        <div class="pull-left">
                          <button data-dismiss="modal" class="btn btn-default" type="button">Fechar</button>
                        </div>
                        <%= link_to raw("Confirmar"), badge, :class => 'btn btn-primary', :'data-method' => 'delete' %>
                      </div>
                    </div>
                  </div>
                </div>
              <% end -%>
            </tbody>
          </table>
          <div class="apple_pagination">
            <div class="page_info">
                <%= page_entries_info @badges %>
            </div>
              <%= will_paginate @badges %>
          </div>
        </section>
      </div>
    </section>
  </div>
</div>

app/views/badges/show.html.erb
<div class="col-lg-12">
  <%= link_to raw("<button type='button' class='btn btn-default'>Voltar</button>"), badges_path %>
  <div class="panel"></div>
	<section class="panel">
    <div class="panel-heading">
        <div class="panel-title">Detalhes</div>
    </div>
    <div class="panel-body form-horizontal">
	      <div class="form-group">
          <label for="number" class="control-label col-lg-3">Nome</label>
          <div class="col-lg-9">
            <label for="number" class="form-control-static"><%= @badge.name %></label>
          </div>
	      </div>
	    	      <div class="form-group">
          <label for="number" class="control-label col-lg-3">Descrição</label>
          <div class="col-lg-9">
            <label for="number" class="form-control-static"><%= @badge.description %></label>
          </div>
	      </div>
	    	      <div class="form-group">
          <label for="number" class="control-label col-lg-3">Imagem</label>
          <div class="col-lg-9">
            <%= image_tag @badge.image.url(:thumb) %>
          </div>
	      </div>
	        </div>
  </section>
</div>